#!/usr/bin/env python3
"""Package the Godot project + GDExtension into a release build.

Builds the C++ GDExtension in release mode, then exports the Godot
project using the headless Godot executable, and zips the result.

Usage:
    uv run package.py            Package for current platform
    uv run package.py windows    Package for Windows
    uv run package.py macos      Package for macOS
    uv run package.py all        Package for all supported platforms
"""

import argparse
import os
import platform
import shutil
import subprocess
import sys
import zipfile

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
DIST_DIR = os.path.join(PROJECT_DIR, "dist")
ADDON_DIR = os.path.join(PROJECT_DIR, "addons", "topdown_sim")

HOST_PLATFORM = {
    "win32": "windows",
    "darwin": "macos",
}.get(sys.platform)


def _find_godot():
    godot = os.environ.get("GODOT_EXE")
    if godot and os.path.isfile(godot):
        return godot
    godot = shutil.which("godot")
    if godot:
        return godot
    candidates = [
        "/c/godot/godot.exe",
        "C:/godot/godot.exe",
        "/usr/local/bin/godot",
        "/Applications/Godot.app/Contents/MacOS/Godot",
    ]
    for c in candidates:
        if os.path.isfile(c):
            return c
    print("Error: Godot executable not found. Set GODOT_EXE env var or add it to PATH.")
    sys.exit(1)


def _build_gdextension():
    """Build the C++ GDExtension in release mode via build.py."""
    print("\n=== Building GDExtension (template_release) ===")
    build_script = os.path.join(PROJECT_DIR, "build.py")
    if not os.path.isfile(build_script):
        print("Error: build.py not found in project root.")
        sys.exit(1)
    result = subprocess.call(
        [sys.executable, build_script, "build", "--target", "template_release"],
        cwd=PROJECT_DIR,
    )
    if result != 0:
        print("Error: GDExtension build failed.")
        sys.exit(1)


def _ensure_export_presets():
    """Create export_presets.cfg if it doesn't exist."""
    presets_path = os.path.join(PROJECT_DIR, "export_presets.cfg")
    if os.path.isfile(presets_path):
        return
    print("Creating default export_presets.cfg...")
    presets_content = """; Auto-generated by package.py — edit in the Godot editor for full options.

[preset.0]

name="Windows Desktop"
platform="windows"
runnable=true
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="dist/windows/TopdownShooter.exe"
patches=PackedStringArray()
encryption_include_filters=""
encryption_exclude_filters=""
script_encryption_key=""

[preset.0.options]

binary_format/embed_pck=true
texture_format/s3tc_bptc=true
texture_format/etc2_astc=false
dotnet/build_server=true
codesign/enable=false
application/modify_resolution=true
application/file_version="1.0.0"
application/product_version="1.0.0"
application/company_name=""
application/product_name="TopdownShooter"
application/file_description=""
application/copyright=""

[preset.1]

name="macOS"
platform="macos"
runnable=false
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="dist/macos/TopdownShooter.app"
patches=PackedStringArray()
encryption_include_filters=""
encryption_exclude_filters=""
script_encryption_key=""

[preset.1.options]

binary_format/embed_pck=true
texture_format/s3tc_bptc=true
texture_format/etc2_astc=true
codesign/enable=false
application/modify_resolution=true
application/icon=""
application/bundle_identifier="com.yourcompany.topdownshooter"
application/bundle_version="1.0.0"
application/copyright=""
application/short_version="1.0.0"
privacy/access_camera=false
privacy/access_microphone=false
"""
    with open(presets_path, "w", encoding="utf-8") as f:
        f.write(presets_content.lstrip())


def _parse_export_presets():
    """Parse export_presets.cfg to find preset names and paths."""
    presets_path = os.path.join(PROJECT_DIR, "export_presets.cfg")
    if not os.path.isfile(presets_path):
        return []
    presets = []
    with open(presets_path, "r", encoding="utf-8") as f:
        current = {}
        for line in f:
            line = line.strip()
            if line.startswith("[preset."):
                if current.get("name"):
                    presets.append(current)
                current = {"index": line[len("[preset."):].rstrip("]")}
            elif line.startswith("name="):
                current["name"] = line.split("=", 1)[1].strip('"')
            elif line.startswith("export_path="):
                current["export_path"] = line.split("=", 1)[1].strip('"')
        if current and current.get("name"):
            presets.append(current)
    return presets


def _export_godot(godot_exe, preset_name, platform_label):
    """Run Godot headless export."""
    print(f"\n=== Exporting Godot project ({platform_label}) ===")
    exe_name = "TopdownShooter.exe" if platform_label == "windows" else "TopdownShooter.app"
    out_path = os.path.join(DIST_DIR, platform_label, exe_name)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    result = subprocess.call(
        [godot_exe, "--headless", "--export-release", preset_name, out_path],
        cwd=PROJECT_DIR,
    )
    if result != 0:
        print(f"Warning: Godot export returned code {result}.")
        print("Make sure export templates are installed: godot --headless --export-release")
        return False
    print(f"Export complete: {out_path}")
    return True


def _package_zip(platform_label):
    """Zip the exported build into dist/<platform>.zip."""
    export_dir = os.path.join(DIST_DIR, platform_label)
    if not os.path.isdir(export_dir):
        print(f"Warning: {export_dir} not found, skipping zip.")
        return
    zip_name = f"TopdownShooter-{platform_label}.zip"
    zip_path = os.path.join(DIST_DIR, zip_name)
    print(f"\n=== Packaging {zip_name} ===")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for root, dirs, files in os.walk(export_dir):
            for f in files:
                file_path = os.path.join(root, f)
                arcname = os.path.relpath(file_path, export_dir)
                zf.write(file_path, arcname)
    print(f"Created {zip_path}")


def _verify_library(target):
    """Check that the built GDExtension library exists for the target."""
    lib_map = {
        "windows": "windows.x86_64",
        "macos": "macos.arm64",
    }
    entry = lib_map.get(target)
    if not entry:
        return True
    gdextension_path = os.path.join(ADDON_DIR, "topdown_sim.gdextension")
    if not os.path.isfile(gdextension_path):
        return False
    with open(gdextension_path, "r") as f:
        content = f.read()
    for line in content.splitlines():
        if line.startswith(entry):
            lib_path = line.split("=", 1)[1].strip().strip('"')
            lib_abs = os.path.join(PROJECT_DIR, lib_path.replace("res://", ""))
            if os.path.isfile(lib_abs):
                return True
            print(f"Warning: Library not found: {lib_abs}")
            return False
    return False


def _validate_target(target):
    """Check if we can build for the given target on this host."""
    cross = {
        "windows": ["macos"],
        "macos": ["windows"],
    }
    if HOST_PLATFORM == target:
        return True
    if target in cross.get(HOST_PLATFORM, []):
        print(f"Warning: Cross-compilation from {HOST_PLATFORM} to {target} "
              "requires a cross-toolchain. Continuing anyway...")
        return True
    print(f"Error: Cannot build for '{target}' on {HOST_PLATFORM}.")
    return False


def cmd_package(targets, skip_build=False, skip_zip=False):
    godot_exe = _find_godot()

    for target in targets:
        if not _validate_target(target):
            continue

        print(f"\n{'='*60}")
        print(f"  Packaging for {target.upper()}")
        print(f"{'='*60}")

        if not skip_build:
            _build_gdextension()

        _ensure_export_presets()
        presets = _parse_export_presets()

        if not presets:
            print("Error: No export presets found in export_presets.cfg")
            sys.exit(1)

        # Match preset by platform
        preset_name = None
        platform_label = None
        target_to_platform = {
            "windows": "Windows Desktop",
            "macos": "macOS",
        }
        for p in presets:
            if p.get("name") == target_to_platform.get(target):
                preset_name = p["name"]
                platform_label = target
                break

        if not preset_name:
            print(f"Available presets: {[p['name'] for p in presets]}")
            print(f"Error: No preset found for platform '{target}'.")
            print("Edit export_presets.cfg or configure in Godot Editor -> Project -> Export.")
            sys.exit(1)

        if not skip_build:
            if not _verify_library(target):
                print(f"Warning: GDExtension library for {target} not found. "
                      "Export may fail or use a stale binary.")

        _export_godot(godot_exe, preset_name, platform_label)

        if not skip_zip:
            _package_zip(platform_label)

    print("\nDone.")


def main():
    parser = argparse.ArgumentParser(description="Package Godot project + GDExtension")
    parser.add_argument("platform", nargs="?", default=None,
                        choices=["windows", "macos", "all"],
                        help="Target platform (default: current host)")
    parser.add_argument("--skip-build", action="store_true",
                        help="Skip GDExtension build (use existing binaries)")
    parser.add_argument("--skip-zip", action="store_true",
                        help="Skip zipping the export output")
    args = parser.parse_args()

    platform_arg = args.platform
    if platform_arg is None or platform_arg == "all":
        if platform_arg == "all":
            targets = ["windows", "macos"]
        else:
            if not HOST_PLATFORM:
                print(f"Error: Unknown platform '{sys.platform}'. Specify target manually.")
                sys.exit(1)
            targets = [HOST_PLATFORM]
    else:
        targets = [platform_arg]

    cmd_package(targets, skip_build=args.skip_build, skip_zip=args.skip_zip)


if __name__ == "__main__":
    main()
